name: Push to DockerHub
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up environment variables
        run: |
          echo "HOST=${{ secrets.HOST }}" > .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
          echo "SCYLLA_URL=${{ secrets.SCYLLA_URL }}" >> .env
          echo "CANVAS_DIM=${{ secrets.CANVAS_DIM }}" >> .env
          echo "CANVAS_ID=${{ secrets.CANVAS_ID }}" >> .env
          echo "COOLDOWN=${{ secrets.COOLDOWN }}" >> .env
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
